export const departments = [
  "Accounting",
  "Anthropology",
  "Applied Chemistry and Chemical Engineering",
  "Arabic",
  "Bangla",
  "Bangladesh Studies",
  "Banking and Insurance",
  "Biochemistry and Molecular Biology",
  "Botany",
  "Chemistry",
  "Communication and Journalism",
  "Computer Science & Engineering",
  "Criminology and Police Science",
  "Development Studies",
  "Dramatics",
  "Economics",
  "Education And Research",
  "Electrical and Electronic Engineering",
  "English",
  "Finance",
  "Fine Arts",
  "Fisheries",
  "Forestry and Environmental Sciences",
  "Genetic Engineering and Biotechnology",
  "Geography and Environmental Studies",
  "History",
  "Human Resource Management",
  "International Relations",
  "Islamic History and Culture",
  "Islamic Studies",
  "Law",
  "Management",
  "Marine Sciences",
  "Marketing",
  "Mathematics",
  "Microbiology",
  "Modern Languages",
  "Music",
  "Oceanography",
  "Pali",
  "Persian Language & Literature",
  "Pharmacy",
  "Philosophy",
  "Physical Education and Sports Science",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Administration",
  "Sanskrit",
  "Sociology",
  "Soil Science",
  "Statistics",
  "Zoology",
];
